---
- name: Install docker dependencies
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add official Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: yes

- name: Add user to docker group to not use sudo
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Set systemd as cgroup driver for docker
  copy: 
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
  notify: Restart docker

